In [ ]:
import pandas as pd
import numpy as np
import math
import scipy.stats as stats

def parameters_initialize():
  u1 = np.random.random(2)
  sigma1 = np.array([[2,1],[1,2]])
  u2 = np.random.random(2)
  sigma2 = np.array([[2,1],[1,2]])
  w0=0.5
  w1 = 1-w0
  return (u1,u2,sigma1,sigma2,w0,w1)
# parameters_initialize()

def calculate_membership(u1,u2,sigma1,sigma2,w0,w1,x):
  norm1= stats.multivariate_normal(mean=u1,cov=sigma1)
  norm2 = stats.multivariate_normal(mean=u2,cov=sigma2)
  Pi = np.zeros((len(x),2))
  # loglk =[]
  for i in range(1,len(x)+1):
    Pi[i-1][0]=(w0*norm1.pdf(x[i-1:i]))/((w0*norm1.pdf(x[i-1:i]))+(w1*norm2.pdf(x[i-1:i])))
    Pi[i-1][1]=(w1*norm2.pdf(x[i-1:i]))/((w0*norm1.pdf(x[i-1:i]))+(w1*norm2.pdf(x[i-1:i])))
    # loglk.append(Pi[i-1][0]*(norm1.logpdf(x[i-1:i])+math.log(w0))+Pi[i-1][1]*(norm2.logpdf(x[i-1:i])+math.log(w0)))
  return Pi
# parameters_initialize()
# print(calculate_membership(u1,u2,sigma1,sigma2,w0,w1,x))


In [ ]:
def update_parameters(Pi,u1,u2,):
  sigma_sum_1 =np.zeros((2,2))
  sigma_sum_2 = np.zeros((2,2))
  for i in range(1,len(x)+1):
    sigma_sum_1 = sigma_sum_1+Pi[i-1,0]*np.matmul((x[i-1:i]-u1.reshape(1,2)).T.values.tolist(),(x[i-1:i]-u1.reshape(1,2)).values.tolist())
    sigma_sum_2 = sigma_sum_2+Pi[i-1,1]*np.matmul((x[i-1:i]-u2.reshape(1,2)).T.values.tolist(),(x[i-1:i]-u2.reshape(1,2)).values.tolist())
  sigma1=sigma_sum_1/sum(Pi[:,0])
  sigma2=sigma_sum_2/sum(Pi[:,1])

  u1[0]= sum(Pi[:,0]*x.iloc[:,0])/sum(Pi[:,0])
  u1[1]= sum(Pi[:,0]*x.iloc[:,1])/sum(Pi[:,0])
  
  u2[0]= sum(Pi[:,1]*x.iloc[:,0])/sum(Pi[:,1])
  u2[1]= sum(Pi[:,1]*x.iloc[:,1])/sum(Pi[:,1])

  w0 = sum(Pi[:,0])/len(Pi)
  w1=1-w0
  return(u1,u2,sigma1,sigma2,w0,w1)







In [ ]:

from google.colab import files 
  
  
uploaded = files.upload()

Saving 2gaussian.txt to 2gaussian.txt


In [ ]:
link="2gaussian.txt"
x=pd.read_csv(link,sep=' ',header=None,names=['D1','D2'])
# print(x)

In [ ]:
def gmm():
  n=0
  u1,u2,sigma1,sigma2,w0,w1=parameters_initialize()
  while n<100:
    Pi=calculate_membership(u1,u2,sigma1,sigma2,w0,w1,x)
    u1,u2,sigma1,sigma2,w0,w1=update_parameters(Pi,u1,u2,)
    n+=1
  return u1,u2,sigma1,sigma2,w0,w1
print(gmm())

# array([7.01314831, 3.98313418]), array([2.99413182, 3.0520966 ]), array([[0.97475893, 0.49747031],
#        [0.49747031, 1.0011426 ]]), array([[1.01023424, 0.02719139],
#        [0.02719139, 2.93782297]]), 0.6652042340621908, 0.33479576593780924)

(array([7.01314831, 3.98313418]), array([2.99413182, 3.0520966 ]), array([[0.97475893, 0.49747031],
       [0.49747031, 1.0011426 ]]), array([[1.01023424, 0.02719139],
       [0.02719139, 2.93782297]]), 0.6652042340621908, 0.33479576593780924)


In [ ]:
def Em_twogmm():
  n=0
  n1=0
  n2=0
  u1,u2,sigma1,sigma2,w0,w1=parameters_initialize()
  while n<30:
    Pi=calculate_membership(u1,u2,sigma1,sigma2,w0,w1,x)
    u1,u2,sigma1,sigma2,w0,w1=update_parameters(Pi,u1,u2,)
    n+=1
  n1=w0*6000
  n2=w1*6000
  return u1,u2,sigma1,sigma2,n1,n2
print(Em_twogmm())

(array([7.01324381, 3.98318875]), array([2.99431576, 3.05207475]), array([[0.97459254, 0.49737587],
       [0.49737587, 1.00106281]]), array([[1.01053826, 0.0271583 ],
       [0.0271583 , 2.93768015]]), 3991.038629745553, 2008.9613702544468)
